name: mapcache-vt CI build

on: 
  push:
    branches: [ multisource ]
    tags:
    - v1.*

jobs:
  # Building using the github runner environement directly.
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: sudo apt-get install apache2-dev libcurl4-openssl-dev libgdal-dev
    - name: Prepare
      run: mkdir build
    - name: Configure
      run: cmake -S. -Bbuild -DWITH_FCGI=0 -DWITH_SQLITE=0 -DWITH_PIXMAN=0 -DWITH_POSTGRESQL=0 -DWITH_BERKELEY_DB=0 -DWITH_MEMCACHE=0 -DWITH_TIFF=0 -DWITH_TIFF_WRITE_SUPPORT=0 -DWITH_GEOTIFF=0 -DWITH_PCRE=0 -DWITH_MAPSERVER=0 -DWITH_RIAK=0 -DWITH_MAPCACHE_DETAIL=0

    - name: Build
      run: make --build build -v
    - name: Install
      run: cmake --build build --target install -v -- DESTDIR=install
